<?php

$requiredFieldsForStarter = array (
    "title" => "Title",
    "name" => "Name",
    "surname" => "Surname",
    "job_title" => "Job title",
    "department" => "Department",
    "manager" => "Manager Name",
    "employment_type" => "Employment Type",
    "start_date" => "Start Date");

$requiredFieldsForLeaver = array (
    "title" => "Title",
    "name" => "Name",
    "surname" => "Surname",
    "job_title" => "Job title",
    "department" => "Department",
    "manager" => "Manager Name",
    "employment_type" => "Employment Type",
    "end_date" => "End Date");

$departments = array (
    "Development",
    "Management",
    "Buyers",
    "Copywriters",
    "Creative",
    "Customer Service",
    "Warehouse",
    "Marketing",
    "HR");

$titles = array (
    "Mr",
    "Mrs",
    "Miss",
    "Ms"
);
$employment_type = array (
    "Permanent Staff",
    "Contractor/Freelancer"
);

$applications = array (
    "admin" => "Admin",
    "jira" => "Discrepancy JIRA",
    "cs" => "Campaign schedule",
    "selligent" => "Selligent",
    "blog" => "The Secret Blog",
    "analytics" => "Google Analytics",
    "github" => "GitHub",
    "email" => "Email"
);

$hardware = array (
    "pc" => "PC",
    "laptop" => "Laptop",
    "mac" => "Mac"
);

$software = array (
    "msoffice" => "MS Office",
    "photoshop"=> "Photoshop"
);